.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. qogecoin_qt test_qogecoin_qt
clean: FORCE
	$(MAKE) -C .. qogecoin_qt_clean test_qogecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_qogecoin_qt_check
qogecoin-qt qogecoin-qt.exe: FORCE
	 $(MAKE) -C .. qogecoin_qt
apk: FORCE
	$(MAKE) -C .. qogecoin_qt_apk
